server.port=8080

# ================= DATABASE (LOCAL) =================
spring.datasource.url=jdbc:mysql://localhost:3306/gymdb
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ================= THYMELEAF =================
spring.thymeleaf.cache=false

# ================= MAIL CONFIG (OPTIONAL LOCAL) =================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gymmanagementproject123@gmail.com
spring.mail.password=wbzrkjodhkvhdfdk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ================= RAZORPAY (DUMMY FOR LOCAL) =================
razorpay.key.id=rzp_test_S4pgVMIeUT02LI
razorpay.key.secret=bnVpnfHCo2evd6QGugctciNL